[package]
name = "clap-colors"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.3", features = ["default", "derive", "wrap_help"] }
color-eyre = { version = "0.6.2" }